import { useEffect, useState } from 'react';
import { jsPDF } from 'jspdf';
import { diagnoseDevice, fetchDevices, fetchReports } from '../api.js';
import { useAuth } from '../AuthProvider.jsx';

const defaultDevice = {
  type: 'Smartphone',
  brand: 'Apple',
  model: 'iPhone 14',
  imei: '357916123456789'
};

function WorkflowDashboard() {
  const { token, user } = useAuth();
  const [devices, setDevices] = useState([]);
  const [currentDevice, setCurrentDevice] = useState(defaultDevice);
  const [report, setReport] = useState(null);
  const [reports, setReports] = useState([]);
  const [status, setStatus] = useState('idle');
  const [message, setMessage] = useState('Choose a device and start diagnostics.');

  useEffect(() => {
    fetchDevices().then((data) => setDevices(data.devices));
    fetchReports().then((data) => setReports(data.reports));
  }, []);

  const totalReports = reports.length;
  const averageScore = totalReports
    ? Math.round(reports.reduce((sum, item) => sum + item.score, 0) / totalReports)
    : 0;
  const lastReportDate = report?.reportDate || reports[0]?.reportDate;

  const handleStartDiagnostics = async () => {
    setStatus('running');
    setMessage('Running device diagnostic sequence...');
    try {
      const payload = {
        imei: currentDevice.imei,
        type: currentDevice.type,
        brand: currentDevice.brand,
        model: currentDevice.model
      };
      const response = await diagnoseDevice(payload, token);
      setReport(response.report);
      setReports((prev) => [response.report, ...prev]);
      setStatus('completed');
      setMessage('Diagnostic completed. Generate a PDF report or continue with another device.');
    } catch (error) {
      setStatus('error');
      setMessage(error.message || 'Diagnostic failed.');
    }
  };

  const generatePdf = (selectedReport) => {
    const doc = new jsPDF({ unit: 'pt', format: 'letter' });
    doc.setFontSize(20);
    doc.text('I-doc Device Diagnostic Report', 40, 50);
    doc.setFontSize(12);
    doc.text(`Generated by: ${user?.name || 'I-doc User'}`, 40, 80);
    doc.text(`Date: ${new Date(selectedReport.reportDate).toLocaleString()}`, 40, 100);

    const lines = [
      `Report ID: ${selectedReport.id}`,
      `IMEI: ${selectedReport.imei}`,
      `Type: ${selectedReport.type}`,
      `Brand: ${selectedReport.brand}`,
      `Model: ${selectedReport.model}`,
      `Health score: ${selectedReport.score}%`,
      `Status: ${selectedReport.status}`,
      `Battery: ${selectedReport.batteryHealth}`,
      `Non-original parts: ${selectedReport.nonOriginalParts}`,
      `Processor test: ${selectedReport.processorTest}`,
      `Camera test: ${selectedReport.cameraTest}`,
      `Screen test: ${selectedReport.screenTest}`,
      `Connectivity: ${selectedReport.connectivityTest}`
    ];

    lines.forEach((line, index) => {
      doc.text(line, 40, 140 + index * 18);
    });

    doc.save(`i-doc-report-${selectedReport.imei}.pdf`);
  };

  return (
    <div className="workflow-card">
      <div className="workflow-header">
        <div>
          <p className="eyebrow">Private diagnostics workflow</p>
          <h3>Welcome, {user?.name}</h3>
          <p className="workflow-intro">Access your secure device inspection dashboard with detailed report export and real-time metrics.</p>
        </div>
        <div className="dashboard-actions">
          <button
            className="button secondary"
            type="button"
            disabled={!report && totalReports === 0}
            onClick={() => generatePdf(report || reports[0])}
          >
            Export current report
          </button>
        </div>
      </div>

      <div className="dashboard-summary-cards">
        <div className="summary-card">
          <span className="summary-label">Total reports</span>
          <strong>{totalReports}</strong>
        </div>
        <div className="summary-card">
          <span className="summary-label">Average health</span>
          <strong>{averageScore}%</strong>
        </div>
        <div className="summary-card">
          <span className="summary-label">Last inspection</span>
          <strong>{lastReportDate ? new Date(lastReportDate).toLocaleString() : 'No tests yet'}</strong>
        </div>
      </div>

      <div className="workflow-body">
        <div className="workflow-form">
          <label>
            Device type
            <select
              value={currentDevice.type}
              onChange={(event) => setCurrentDevice((prev) => ({ ...prev, type: event.target.value }))}
            >
              <option>Smartphone</option>
              <option>Tablet</option>
              <option>Wearable</option>
            </select>
          </label>
          <label>
            Brand
            <input
              type="text"
              value={currentDevice.brand}
              onChange={(event) => setCurrentDevice((prev) => ({ ...prev, brand: event.target.value }))}
            />
          </label>
          <label>
            Model
            <input
              type="text"
              value={currentDevice.model}
              onChange={(event) => setCurrentDevice((prev) => ({ ...prev, model: event.target.value }))}
            />
          </label>
          <label>
            IMEI
            <input
              type="text"
              value={currentDevice.imei}
              onChange={(event) => setCurrentDevice((prev) => ({ ...prev, imei: event.target.value }))}
            />
          </label>
          <button className="button primary" type="button" onClick={handleStartDiagnostics}>
            Run Diagnostics
          </button>
          <p className={`workflow-message ${status}`}>{message}</p>
        </div>

        <div className="workflow-summary">
          <h4>Latest diagnostic snapshot</h4>
          {report ? (
            <>
              <div className="report-grid">
                {[
                  ['Status', report.status],
                  ['Health score', `${report.score}%`],
                  ['Battery', report.batteryHealth],
                  ['Non-original parts', report.nonOriginalParts],
                  ['Processor', report.processorTest],
                  ['Camera', report.cameraTest],
                  ['Screen', report.screenTest],
                  ['Connectivity', report.connectivityTest]
                ].map(([label, value]) => (
                  <div key={label} className="report-cell">
                    <span>{label}</span>
                    <strong>{value}</strong>
                  </div>
                ))}
              </div>
              <div className="report-footer">
                <button className="button secondary" type="button" onClick={() => generatePdf(report)}>
                  Export PDF Report
                </button>
              </div>
            </>
          ) : (
            <p>Select a device and run diagnostics to see results here.</p>
          )}
        </div>
      </div>

      <div className="report-history">
        <div className="report-history-header">
          <h4>Recent reports</h4>
          <span className="report-count">{totalReports} total</span>
        </div>
        <div className="report-list">
          {reports.length === 0 && <p>No reports created yet.</p>}
          {reports.map((entry) => (
            <article key={entry.id} className="report-item">
              <div>
                <strong>{entry.brand} {entry.model}</strong>
                <p>IMEI {entry.imei}</p>
              </div>
              <div className="report-item-actions">
                <span className="report-score">{entry.score}%</span>
                <button className="button secondary" type="button" onClick={() => generatePdf(entry)}>
                  Download PDF
                </button>
              </div>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}

export default WorkflowDashboard;
